app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/cms
    username: postgres
    password: Matei2004
    driver-class-name: org.postgresql.Driver

  jpa:
    # This is the "No Migration" setting.
    # It checks your Java classes and updates the DB schema automatically.
    hibernate:
      ddl-auto: update

    # Helpful to see the SQL Spring generates in your console
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true